import type { Metadata } from "next";
import "../globals.css";
import MainHeader from "@/components/main-header/page";
import MainFooter from "@/components/main-footer/page";

export const metadata: Metadata = {
  title: "Main layout",
  description: "Generated by Main layout",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="root">
          <MainHeader />
          <main> {children}</main>
          <MainFooter />
        </div>
      </body>
    </html>
  );
}
