import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Main layout",
  description: "Generated by Main layout",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <div className="min-h-screen max-w-7xl mx-auto px-4 py-6">
          <header className="mb-6">
            <h1 className="text-3xl font-bold">🌐 My Website</h1>
          </header>
          <main>{children}</main>
          <footer className="mt-10 border-t pt-4 text-center text-sm text-gray-500">
            © 2025 My Company. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
